language: csharp

solution: ActionRpgKit.sln

# Environment variables
env:
  global:
  - GH_REPO_NAME: ActionRpgKit
  - DOXYFILE: "$TRAVIS_BUILD_DIR/config.dox"
  - GH_REPO_REF: github.com/PaulSchweizer/ActionRpgKit.git
  - secure: NQSmLmhKl0mwXYS2maNznL3orn+gbowXwTsOzQM1CIQXQssoeTIgNjURYO9AfxgXScxMjGR11B+nCG40lCrL9zK3cDfgJVzk2dHPyYtjeb+GqjAn2PCVZFAB6N4SYEGU88bLhHzAvU3keSzLADkciDwRnWdSeBmBoUPWDTIfWAdUUgf5DekRLQLriHn4WukzxhDmFP7+SvmefEV3g5950FGsg+iceh1eiTUaRq/5zE2XXXLV6Sq3glSqk2hRLimaXRHZn2sF61JZoalovn9erh9Jm+lwO8VBYo+nYPkT5EGWOcNz8pcnlQzCAnLJ5kNLrJZMb7l1oDJ7y7ZBkw6VLfTimTGAue7opzzHnprTuF6Yrps4TPRGKO4PD567p8qNoqZZCXQoooEnCUm73F3hUUQ/YcD0m45ueFWwvOdhQexjxz304fF0YW0H2DYjbFs7KapovFPtTLdBJwduVqPcJ8/vMUG25th1RleP/fCSFMD9Y52/0O1M7W2Y+1Bj4qHkZMMgGnmCWkYOGxLlx1LGlnxpvKGtluQyQXdRziYJ2JRKVXOdMl7QgfIJ/R6lVJbVjI5iVWftT1PkR3QyUPPnnVoMNEjQ6Sr/MDfSCzGC2MjEQLvZ/TZXGr4fQHqJ1qQXUtk9qNMkmuOTx+Gn2ihEI/FtEGk6Yyt0r99GXa2AvOM=

before_install:
    - sudo apt-get update
    - sudo apt-get install doxygen
    - sudo apt-get install graphviz
    - sudo apt-get update

install:
  - nuget restore ActionRpgKit.sln
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd ../../csMACnz/Coveralls.net-Samples

# Build your code e.g. by calling make
script:
  - xbuild /p:Configuration=Release ActionRpgKit.sln
  - export LD_LIBRARY_PATH=/usr/local/lib
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+ActionRpgKit ./src/packages/NUnit.Console.3.0.0-beta-3/tools/nunit-console.exe --process=Single $TRAVIS_BUILD_DIR/ActionRpgKit/bin/Debug/ActionRpgKit.dll
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - cat monocovCoverage.cov
  - ls monocovCoverage
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $REPO_COMMIT_AUTHOR
  - echo $REPO_COMMIT_AUTHOR_EMAIL
  - echo $REPO_COMMIT_MESSAGE
  - echo $TRAVIS_JOB_ID
  - mono ./src/packages/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci  --useRelativePaths

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod 777 generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

# Blacklist
branches:
  except:
  - gh-pages
