language: csharp
solution: ActionRpgKit.sln
mono:
  - 2.10.8
script:
  - xbuild /p:Configuration=Debug ActionRpgKit.sln
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore ActionRpgKit.sln
after_script:
  - nunit-console 
