version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: ccQ+As60wXwW+67I7IMmQUlt+z2qXhI4GKLsbMPr13JitDr3MLgx8jXcGCZCfrMm
before_build:
  - nuget restore "ActionRpgKit.sln"
build:
  project: ActionRpgKit.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:""ActionRpgKit/bin/Release/ActionRpgKit.dll"" /noshadow" -filter:"+[ActionRpgKit*]*" -output:opencoverCoverage.xml
   
    $coveralls = (Resolve-Path "./packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken ccQ+As60wXwW+67I7IMmQUlt+z2qXhI4GKLsbMPr13JitDr3MLgx8jXcGCZCfrMm --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

